{
 "title": "test prometheus prom labs",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "Salle de l'IRM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Température de la salle IRM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature_IRM", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Température de la salle IRM (historique)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "temperature_IRM", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Humidité de la salle IRM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "humidity_IRM", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Humidité dans la salle (Historique)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "humidity_IRM", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Débit chiller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Débit d'eau dans le chiller",
     "type": "table",
     "gridPos": { "h": 6, "w": 9, "x": 1, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "flowlpm" } },
     "targets": [
      {
       "expr": "topk (3, sum by(path, method) (rate(demo_api_request_duration_seconds_count[5m])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Température chiller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Température eau",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature_input", "legendFormat": "__auto" },
    { "expr": "temperature_output", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Température eau (historique)",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 19 },
   "targets": [
    { "expr": "temperature_input", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Température de l'eau",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 25 },
   "targets": [
    { "expr": "temperature_input", "legendFormat": "__auto" },
    { "expr": "temperature_output", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_log_enabled[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Historique",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true
  }
 ]
}